# This workflow will automate the publishing of a Markerator based website.

name: Markerator Automation

on:
  push:
    branches:
     - input

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Markerator and investigate directories
      run: |
        ls -al
        git clone https://github.com/benpocalypse/Markerator.git .
        ls -al

    - name: Checkout input branch
      uses: actions/checkout@v3
      with:
        path: input

    - name: Investigate directories 1
      run: ls -al

    - name: Checkout output branch
      uses: actions/checkout@v3
      with:
        branch: output
        path: output

    - name: Investigate directories again
      run: ls -al
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Markerator
      run: dotnet run -t Bengineering -i index.md --favicon true -op About.md --posts true -pt News

    - name: Final directories investigation
      run: |
        ls -al
        cd output
        ls -al
        cd ..
        ls -al
        cd ..
        ls -al
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: output
        directory: output
