# This workflow will automate the publishing of a Markerator based website.

name: Markerator Automation

on:
  push:
    branches:
     - input

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Clone Markerator and investigate directories
      run: |
        ls -al
        git clone https://github.com/benpocalypse/Markerator.git .
        ls -al

    - name: Checkout input branch
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        path: input
        ref: input

    - name: Investigate directories 1
      run: ls -al

    - name: Checkout output branch
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        path: output
        ref: output

    - name: Investigate directories 2
      run: |
        ls -al
        cd output
        ls -al
        git status
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Markerator
      run: dotnet run -t Bengineering -i index.md --favicon true -op About.md,Contact.md --posts true -pt News -u https://bengineeri.ng -rss true -ri true

    - name: Final directories investigation
      run: |
        ls -al
        git branch
        cd output
        ls -al
        git branch
        git pull
        git status
        git checkout output
        git add *
        git branch
        git status
        
    - name: Commit and push changes
      run: |
        git config user.name ${{ secrets.USERNAME }}
        git config user.email github-actions@github.com
        ls -al
        cd output
        git branch
        git checkout output
        git branch
        ls -al
        git commit -m "Automated commit with Markerator"
        git push
        
